### ISSUE TITLE
Feature Request: Binary attachments for documents

### ISSUE THREAD

**Issue by mrwunderbar666** [ccs-amsterdam/amcat4#25]
Content analysis can often go beyond texts. Think of manual coding jobs where we would like to annotate content that also features images (e.g., instagram posts). Sound files or PDFs (OCR content) might also be candidates.

Elastic comes with the [necessary features](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/binary.html) for this, and there is also a [plugin available](https://www.elastic.co/guide/en/elasticsearch/plugins/7.17/ingest-attachment.html) for ingestion. I guess it would be necessary to limit the file size to prevent users from accidentially uploading ridiculously large attachments.

This is not urgent, but I think worth considering.

**Comment by vanatteveldt** [comment]
We've been pondering this for a bit. I was thinking using external storage and a url could be easier to handle very large sets (e.g. videos), but it might be interesting to have a within-elastic option as well

**Comment by vanatteveldt** [comment]
We've added an option to integrate a minio / S3 storage, including pre-signed GET and POST for reading/adding multimedia

**Comment by vanatteveldt** [comment]
I think this should solve your usecase, so closing the issue for now
