### ISSUE TITLE
object fields can not be hidden

### ISSUE THREAD

**Issue by JBGruber** [ccs-amsterdam/amcat4#37]
I thought at first that this was an `amcat4client` issue, but the browser shows me an internal server error. In the amcat logs the error is:

```
elasticsearch.BadRequestError: BadRequestError(400, 'mapper_parsing_exception', 'Mapping definition for [dfm] has unsupported parameters:  [meta : {amcat4_display_meta=0}]')
```

steps to reproduce:

1. run the actioncat example action: https://github.com/ccs-amsterdam/actioncat/tree/main#r-action-example-tidy-document-features
2. go to the web interface and try to hide the dfm field (Fields -> Show in article)

**Comment by vanatteveldt** [comment]
In fact, it's probably a good idea to move all these instance-level field settings to the system index rather than (ab)using the mapping. This would also hold for determining which fields should be hidden from the metareader

**Comment by vanatteveldt** [comment]
I assume this issue disappeared as we no longer store this info in the meta
