### ISSUE TITLE
Fix highlighting in query results

### ISSUE THREAD

**Issue by vanatteveldt** [ccs-amsterdam/amcat4#42]
Current system is a bit of a mess with
- highlight param is either dict or bool
- highlighting has an unclear relation with annotations

Solution:
- drop all annotations
- highlight as enum {none, highlights, snippets} , of highlight={type: [enum], ...}

**Comment by vanatteveldt** [comment]
@kasperwelbers I think you implemented this, correct?

**Comment by kasperwelbers** [comment]
I think I did. Internally it might still look complicated because the elastic highlight mechanic is related to the snippet mechanic. But I think its now robust, and no longer confusing in our api. 

So if you agree with the solution we can close this
